SWARM-1108 Modified keycloak-server fraction for the theme customization functionality to work (#665)
SWARM-1108: Modified keycloak-server fraction for the theme customization functionality to work

Motivation- The keycloak theme customization while using Wildfly Swarm option is completely broken now and throws a NoClassDefFoundError

Modifications
Changed the module.conf of the keycloak-server fraction to include export=true

Result
The NoClassDefFoundError is no longer thrown and it's possible to use custom themes now using the parameters given in the reference