SWARM-582: Webservices fraction should bundle org.jboss.ws.saaj-impl module.
Motivation
----------
While having an EJB invoking an external SOAP service, the following exception is thrown:

org.jboss.modules.ModuleNotFoundException: org.jboss.ws.saaj-impl:main

Modifications
-------------
Added org.jboss.ws.saaj-impl:main module to webservices/module.conf

Result
------
Module org.jboss.ws.saaj-impl is now available when the webservices fraction is used